### ISSUE TITLE
spiral module installations (can't get it to install showing errors) 

### ISSUE THREAD

**Issue by VaibhaviRaut** [SCANL/swum_project#1]
spiral module installations (can't get it to install showing errors) 

<img width="1420" alt="Screen Shot 2020-08-31 at 1 24 14 PM" src="https://user-images.githubusercontent.com/46416596/91748053-4fcd6b80-eb8d-11ea-9714-13536470cfcb.png">
<img width="1420" alt="Screen Shot 2020-08-31 at 1 24 22 PM" src="https://user-images.githubusercontent.com/46416596/91748057-50660200-eb8d-11ea-99a2-c75a45decb23.png">

**Comment by BrianPopeck** [comment]
The Spiral module that this project uses isn't hosted on PyPI, so `pip install spiral` tries to install an unrelated Python package also named spiral. 

See installation instructions for the right module here - https://github.com/casics/spiral#-installation-instructions

**Comment by VaibhaviRaut** [comment]
Thank you! :)
